- batocera-systems/Resources/batocera-systems.json
- emulatorLauncher/Generators/Xemu.Generator.cs
xemu generator:
- Fix check for flashPath (was checking eeprompath)
systems.JSON
Updated list of BIOS and several md5 (source used = libretro doc + batocera)
> Small fix in xemu generator + rework of systems.JSON (BIOS)

- emulatorLauncher/Generators/Pcsx2.Generator.cs
- emulatorLauncher/Generators/Rpcs3.Generator.cs
- Fix (wild cards hack, half pixel offset, half bottom override, round sprite offset, merge pp sprite, disable safe features, texture offsets, skip draw,)
- Automatically activate user hacks if one of the user hacks feature is selected (else the feature will not work)
> FIX PCSX2 generator for user hacks features and fix rpsc3 generator (features inverted)

- emulatorLauncher/Generators/Dolphin.Controllers.cs
When setting "real wiimotes", the wiimote sections in the WiimotNew.ini files get wrongly created:
- Section gets created as [ [ WiimoteX] ] instead of [ WiimoteX ]
- Starts with Wiimote0 instead of Wiimote1
> Fix real wiimotes ini generator

- batocera-systems/Resources/batocera-systems.json
bios should be in \dc\ subfolder for dreamcast
> Corrected bios folder for dreamcast

- batocera-systems/Resources/batocera-systems.json
Previously only fbneo bios were listed, added neocd requirements in \bios\neocd folder. https://github.com/libretro/neocd_libretro
> Update bios list for neocd

- batocera-systems/Resources/batocera-systems.json
BIOS for same_cdi are located in \bios\same_cdi\bios BIOS list is the same as for mame core but the core does not use hash list.
> Added bios check for same_cdi core

- batocera-systems/Resources/batocera-systems.json
- emulatorLauncher/Generators/Oricutron.Generator.cs
- emulatorLauncher/Generators/Yuzu.Controllers.cs
- emulatorLauncher/Generators/Yuzu.Generator.cs
- emulatorLauncher/emulatorLauncher.csproj
Update of yuzu for controllers, working correctly for XInput (tested with ONE S, 360 and 8BitDo in XInput mode) and other sdl controllers (tested with PS4, PS5 and Switch Pro)
> Yuzu controller

- emulatorLauncher/Generators/Pcsx2.Controllers.cs
Simplification : all controllers can be injected as SDL, even XInput
> Fix PCSX2 controllers index - inject every controller as SDL

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Demul.Generator.cs
For dreamcast, DEMUL was sending wrong run command: 
was run=dreamcast -rom""
Should have been run=dc -image""
Addition of extra features for demul emulator also
> DEMUL fix for running dreamcast roms + added features

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/BigPEmu.Generator.cs
- emulatorLauncher/Generators/Pcsx2.Generator.cs
- correction for skipdraw feature in pcsx2 v1.6 ==> name of parameter in .ini is different
- Add one value in pcsx2 1.7 version for skipdraw for bully game (as per pcsx2 wiki : https://wiki.pcsx2.net/Bully
Skipdraw 6 : 6 can be used to correct an active bug "Misaligned depth blur effect"
> PCSX2 - skipdraw feature

- .emulationstation/es_features.cfg
- batocera-systems/Resources/batocera-systems.json
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
- emulatorLauncher/Generators/LibRetro.Generator.cs
- emulatorLauncher/Generators/Yuzu.Generator.cs
**For yuzu** : 
add cpu accuracy feature
**For FUSE:**
Add Machine feature.
For controls:
refer to https://docs.libretro.com/library/fuse/#controllers-usage
> There are some conflicts in the way the input devices interact because of the use of the physical keyboard keys as joystick buttons. For a good gaming experience, set the user device types as follows:
For joystick games: Set user 1 to a joystick type. Optionally, set user 2 to another joystick type (local cooperative games). Set user 3 to none. This way, you can use L1 as RETURN, R1 as SPACE, and SELECT to bring the embedded keyboard.
For keyboard games: Set users 1 and 2 to none, and user 3 to Sinclair Keyboard. You won't have any joystick and the embedded keyboard won't work, but the entire physical keyboard will be available for …
> Fuse core options + controls and yuzu cpu accuracy feature

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/LibRetro.Generator.cs
minor optimizations:
add game focus global feature for retroarch and set it on "detect" by default
remove rewind feature because with dosbox it create and infinite loop of annoynig savestate error messages
> add game focus to retroarch global features & roland sc-88 sound font, remove rewind feature for dos

- .emulationstation/es_features.cfg
fix options not showing for megadrive and megadrive msu
> corrections in genesis_plus_gx core for multiple system names

- .emulationstation/es_features.cfg
- batocera-systems/Resources/batocera-systems.json
- emulatorLauncher/Generators/Dolphin.Generator.cs
- emulatorLauncher/Generators/Duckstation.Generator.cs
- emulatorLauncher/Generators/Model3.Controllers.cs
Add sysconf sensorbar position feature for dolphin wii.
Supermodel use correct index.
Apple2GS add missing bios check
Fix duckstation savespath (we were changing 2x \\ to \\\\)
> Dolphin sensorbar, supermodel index, duckstation savespath, apple2gs bios

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
- emulatorLauncher/Generators/Ryujinx.Controllers.cs
Vice features (common to the 3 cores): warp boost, aspect ratio, crop, crop mode, gfx color depth, retropad options)
Vice per core:
- - model
- - ram extension
- - palette
Ryujinx:
Add Feature to revert ABXY for XBOX controllers so that button matches name of button instead of position
> vice (xvic, x64, xplus4) features and ryujinx buttons inversion feature

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
Added vice_xpet and vice_x128 features.
Added vice_x64sc features (same as vice_x64).
Fuse : switch default controller type to Kempton instead of Sinclair1, as it was before, it was more common joystick type and works in more games.
> Finalization of vice cores features

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Cemu.Generator.cs
- emulatorLauncher/Generators/Yuzu.Generator.cs
Fix renderer choice in yuzu and fix default value to false to avoid this case in the future.
Even when default = false, the default value works properly.
Added missing resolutions, MSAA option, vsync feature, audio driver and output.
cemu: force disabling update check
> Yuzu features injection fix (\default issue)

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Dolphin.Controllers.cs
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
- emulatorLauncher/Generators/LibRetro.Generator.cs
- emulatorLauncher/Generators/Rpcs3.Generator.cs
- emulatorLauncher/Generators/TeknoParrot.generator.cs
- Reenable OSD messages by default
- Add RPCS3 features (wake-up delay and time stretching)
- Add TATE MODE (vertical screen) for flycast, fbneo, fbalpha and fbalpha2012
- Add option to disable RequiresAdmin in Teknoparrot
- Inject dolphin hotkeys
> Libretro, rpcs3, dolphin and Teknoparrot

- .emulationstation/es_features.cfg
- batocera-systems/Resources/batocera-systems.json
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
- emulatorLauncher/Generators/Libretro.Controllers.cs
- Finalization of choice of controller type for cores where we have generator
- Fixed many default features values in EL (value was not in the list of values available in RetroArch core options, or typo errors (capital letters...)).
- Added shared feature for turbo button (only available for FCEUMM yet
- Added bios check for Gearcoleco (mandatory bios for this core)
> Features cleanup & finalization + extras

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Cemu.Controllers.cs
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
**Add controller choice for player 1 & player 2:**
Some games do not accept 2 gamepads in multiplayer (e.g. mario kart). Other games accept ONLY pro controllers in multiplayer (e.g. New super mario wiiu)
**Add wiimotes feature**
Possibility to use wiimotes in CEMU, however as wiimotes are not recognized in ES, it's either wiimotes or gamepad configuration.
If user sets wiimotes ==> all controllers will be set to real wiimotes.
Same principle as Dolphin.
> cemu - controller stuff

- .emulationstation/es_features.cfg
- emulatorLauncher/Common/ConfigFile.cs
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
- emulatorLauncher/Generators/LibRetro.Generator.cs
- emulatorLauncher/Generators/Mame64.Generator.cs
- emulatorLauncher/Generators/MessSystem.cs
- emulatorLauncher/Generators/Pcsx2.Generator.cs
- emulatorLauncher/Generators/Xemu.Generator.cs
- emulatorLauncher/Generators/Yuzu.Controllers.cs
PCSX_REARMED:
- Added game fix features
CHEATS PATH
- Moved cheats path to RetroBat \cheats folder for RetroArch & PCSX2
MAME64
- Add commandline arguments also for MESS systems when using mame64
- Add bgfx shaders features
- Add other features
YUZU
- fixed motion not working (additional space)
> Cheats path harmonization, pcsx_rearmed game fixes feature and MAME64 stuff

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
- emulatorLauncher/Generators/Mame64.Generator.cs
- emulatorLauncher/Generators/MessSystem.cs
- emulatorLauncher/Generators/Pcsx2.Generator.cs
- emulatorLauncher/Installer.cs
MAME64:
- add per-game controller profile
- add frequency to resolution (using videomode)
- cleanup of code
- Add one additional artowrk path in saves\mame\ for people wanting to use mame artworks instead of bezels
- disable libretro -artpath command line if a bezel is used to not combien bezel & artwork
PCSX2:
- Add management of new pcsx2 executable (pcsx2-qt.exe)
- Correction of bilinear filtering feature (it has 3 choices in pcsx2)
> MAME64 & PCSX2 stuff

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Mame64.Generator.cs
- emulatorLauncher/Generators/MessSystem.cs
Fix 1: ratio, when ratio in mame system set to AUTO and global settings ratio set, wrong "ratio" value was  sent to Mame
Fix 2: -artpath was not correctly set when running MESS systems with MAME standalone & libretro:MAME
> 2 fixes for Mame

- emulatorLauncher/Generators/Duckstation.Generator.cs
- emulatorLauncher/Generators/Mame64.Generator.cs
- emulatorLauncher/Generators/Pcsx2.Controllers.cs
- emulatorLauncher/Generators/Uae.Generator.cs
- emulatorLauncher/Generators/Yuzu.Controllers.cs
Mame standalone - do not remove emulator artwork path - was breaking bgfx shaders
WINUae: fix running .uae extensions
PCSX2 & yuzu: add exit shortcut
> Mame standalone - do not remove emulator artwork path - was breaking bgfx shaders

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Citra.Generator.cs
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
- emulatorLauncher/Generators/Mame64.Bezels.cs
- emulatorLauncher/Generators/Ppsspp.Generator.cs
- emulatorLauncher/Generators/Rpcs3.Generator.cs
- emulatorLauncher/Generators/Ryujinx.Generator.cs
- emulatorLauncher/Generators/Yuzu.Generator.cs
- emulatorLauncher/emulatorLauncher.csproj
yuzu - add ratio
global: changed some features to "preset=switch"
> citra - align paths with libretro paths

- emulatorLauncher/Generators/AmigaForever.Generator.cs
if amiga forever executable is not found in the default emulators folder, the launcher will look for it in programFilesX86 and use that path as fallback
> use programFilesX86 path as fallback
