fabricecaruso/batocera-ports

emulatorLauncher/Generators/LibRetro.CoreOptions.cs

- add mame, snes9x, genesis plus gx, genesis plus gx, potator
- some modifications to mednafen psx

new cores integration

---

emulatorLauncher/Generators/NosGba.Generator.cs

Generator no$gba
Argument "/2" added  for gba2player system.

/2 argument added

---

emulatorLauncher/Generators/LibRetro.CoreOptions.cs
emulatorLauncher/Generators/Pcsx2.Generator.cs
emulatorLauncher/Generators/Rpcs3.Generator.cs

3 additions in rpcs3generator:
- Features injections in config.yml
- Set options in currentsettings.gui to disable emulator prompts (update, welcome screen, confirm rom load and exit)
- Add check if firmware is installed, if not installed & firmware exists in \bios path then run commandArray to install firmware on first launch instead of running game
Added custom textures code for:
- mednafen_psx_hw
- pcsx2

Update Rpcs3.Generator, libretro core options and pcsx2 generator

---

emulatorLauncher/Generators/Pcsx2.Generator.cs
emulatorLauncher/Generators/Ryujinx.Generator.cs

PCSX2:
- Add comments
- Add CRC hack
- Aligned user hacks between both versions of PCSX2
RYUJINX:
Added all emulator features

PCSX2 Generator + Ryujinx features integration

---

emulatorLauncher/Generators/Cemu.Generator.cs

Add the following features in settings.xml for cemu:
- Graphic driver (+ vsync, async shader compilation and choice of upscale/downscale filter)
- Audio driver (incl. channel selection)
- Console language
- cemu UI notifications / statistics activation

Add cemu emulator features

---

emulatorLauncher/Generators/LibRetro.CoreOptions.cs
emulatorLauncher/Generators/Rpcs3.Controllers.cs
emulatorLauncher/Generators/Rpcs3.Generator.cs
emulatorLauncher/Generators/vita3k.Generator.cs
emulatorLauncher/Installer.cs
emulatorLauncher/emulatorLauncher.csproj

Addition of following swanstation features:
- resolution scaling
- force NTSC timings
- Widescreenhack
- msaa
Vita3k generator: added game installation and check if game is installed

Libretro core options for swanstation and psvita game install automation

---

emulatorLauncher/Generators/Pcsx2.Controllers.cs
emulatorLauncher/Generators/Pcsx2.Generator.cs
emulatorLauncher/emulatorLauncher.csproj

Add PCSX2QT autoconfiguration of controllers (SDL & XInput)

PCSX2QT controller autoconfiguration

---

emulatorLauncher/Generators/Pcsx2.Controllers.cs

No need for reversebutton : managed by PCSX2
Input.Id 4 & 7 correction

PCSX2 last input correction

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/Citra.Generator.cs
emulatorLauncher/Generators/Ryujinx.Controllers.cs
emulatorLauncher/Generators/Ryujinx.Generator.cs
emulatorLauncher/Generators/Xenia.Generator.cs
emulatorLauncher/emulatorLauncher.csproj

Ryujinx:
- add controller autoconfig
- add es_features : rumble, motion, console region
Dolhpin-emu:
- add vsync in es_features

Ryujinx controllers + vsync feature on dolphin-emu

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/BigPEmu.Generator.cs
emulatorLauncher/Generators/Xenia.Generator.cs

- Argument -localdata added
- Also changed bezel to apply only when in borderless window
- Removed duplicate line for _resolution

BigPemu update for local storage of config file

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/Model3.Controllers.cs
emulatorLauncher/Generators/Model3.Generator.cs
emulatorLauncher/emulatorLauncher.csproj

Added a few features (throttle, new3Dengine), force dir to rompath model3 for UI and added better default controller configuration.

Model 3 controller configuration + features

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/BigPEmu.Generator.cs

Reshade for bigpemu

---

.emulationstation/es_features.cfg
batocera-systems/Program.cs
batocera-systems/Resources/batocera-systems.json
emulatorLauncher/Generators/Phoenix.Generator.cs
emulatorLauncher/Installer.cs
emulatorLauncher/Program.cs

- added bios check for jaguar
- manage unzipping
- manage dynamic content of .cue file
- manage also jaguar system

Fix phoenix generator and activate for jaguar

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/vita3k.Generator.cs

Initiate module management in yml config file and addition of 1 module required to fix SF vs Tekken

Vita3k - yml modules management

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/LibRetro.CoreOptions.cs
emulatorLauncher/Generators/LibRetro.Generator.cs

mostly audio options
remove rewind feature (seems to be not compatible with scummvm)

add features for scummvm core

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/LibRetro.CoreOptions.cs

Fix fba2012cps2 features

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/Pcsx2.Controllers.cs
emulatorLauncher/Generators/Uae.Generator.cs

- PCSX2 controller index from SDL
- Missing fullboot feature for pcsx2-QT
- add cycle exact feature for WinUAE

Minor fixes

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/Dolphin.Generator.cs

Add feature to set wii language

Dolphin - set wii language

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/LibRetro.CoreOptions.cs

Desmume : add features for touchscreen, resolution, screen layout & msaa
Libretro dolphin : add wii controller type choice
melonds: add screen layout and touchscreen emulation mode

desmume, melonds, libretro-dolphin

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/LibRetro.CoreOptions.cs
emulatorLauncher/Generators/Yuzu.Controllers.cs

- YUZU generator: allow inversion of A/B/X/Y as a feature
- vecx core : add res_multiplier features
- tyrquake : add resolution and controls features
- tgbdual: added feature for screen layout
- snes9x: fix audio interpolation values & added missing joypad/mouse controller selection

Yuzu buttons inversion + vecx & tyrquake features

---

.emulationstation/es_features.cfg
batocera-systems/Resources/batocera-systems.json
emulatorLauncher/Generators/LibRetro.CoreOptions.cs
emulatorLauncher/Generators/LibRetro.Generator.cs

emuscv : added core & features & bios check
Features for: 
- craft : added features (port)
- mrboom: added features (port)
- swanstation
- stella
- stella2014
- same_cdi
- sameduck
- race
- 81
- wasm4

emuscv core + features for multiple cores

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/LibRetro.CoreOptions.cs

Features for:
- px68k
- quasi88
- prboom

Core features

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/Citra.Generator.cs
emulatorLauncher/Generators/Dolphin.Controllers.cs
emulatorLauncher/Generators/Libretro.Controllers.cs
emulatorLauncher/emulatorLauncher.csproj

Added to 5 snes cores:
- bsnes
- snes9x
- bsnes_hd_beta
- mesen-s
- mednafen_snes
Added citra custom textures.
Dolphin:
- Add shake for side layout (l2 button)

snes switch buttons, dolphin controls & citra custom textures

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/Citra.Generator.cs
emulatorLauncher/Generators/LibRetro.CoreOptions.cs
emulatorLauncher/Generators/Xemu.Generator.cs

Additional features for:
- PUAE
- prosystem
- Potator
- bsnes
- bsnes_hd_beta
- ppsspp
- picodrive
XEMU:
- Add language change in eeprom
- refactoring
- add vsync feature
- Disable writing of dvd_path in toml file as this breaks new versions

Additional core features + XEMU stuff

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/LibRetro.CoreOptions.cs

Cores features

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/LibRetro.CoreOptions.cs

FinalBurn: Choose between classic and modern controllers
PCSX2: add new resolution options
Added features for:
- Opera
- 4DO
- a5200
- atari800
- mgba

More core features

---

.emulationstation/es_features.cfg
batocera-systems/Resources/batocera-systems.json
emulatorLauncher/Generators/LibRetro.CoreOptions.cs
emulatorLauncher/Generators/MessSystem.cs

When using .rpk file, command line must be -cart <full rompath>

Messsystems add .rpk for TI99

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/LibRetro.CoreOptions.cs
emulatorLauncher/Generators/LibRetro.Generator.cs
emulatorLauncher/Generators/MessSystem.cs

- MESS systems, small fixes
- Defined list of systems with automatic game focus enabling
- AUDIO LOW-PASS Filter feature harmonization
- Additional controller type options

Add disableautocontrollers to supermodel + Mess systems + features

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/LibRetro.CoreOptions.cs
emulatorLauncher/Generators/Libretro.Controllers.cs
emulatorLauncher/Generators/Pcsx2.Generator.cs

- Fix FM77AV machine shortname
- PCSX2: added 2 requested features

BETA fixes (part1)

---

.emulationstation/es_features.cfg
batocera-systems/Resources/batocera-systems.json
emulatorLauncher/Generators/LibRetro.CoreOptions.cs
emulatorLauncher/Generators/LibRetro.Generator.cs
emulatorLauncher/Generators/MessSystem.cs

- Add parallel_n64 64DD feature
- Add XEGS system
- Add code to force softlist usage for MESS systems and softlist values in es_features
- Add adam & archimedes

Additions (64DD + softlists for mess + xegs system)

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/LibRetro.CoreOptions.cs
emulatorLauncher/Generators/Pcsx2.Generator.cs

- inputremap_port, set player port consistently with playerindex input_remap_port_p1 = playerindex - 1
- vice
- Handy
- mame2003 (TATE MODE)
- dosbox pure controller types
- PCSX2: for custom textures add choice to disable precaching textures

Fix input_remap_port & Features

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/LibRetro.CoreOptions.cs
emulatorLauncher/Generators/Mame64.Generator.cs
emulatorLauncher/Generators/ScummVm.Generator.cs

scummvm:
- add feature to bypass message for games that are not fully supported
MAME64:
- Add "almost" all command line options & associated features

scummvm and mame standalone

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/Mame64.Generator.cs

- add startup in maximized window
- add bezels
- add features for MESS systems
- fix MESS feature grouping (missing group ADVANCED SETTINGS)

Mame standalone

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/Citra.Generator.cs
emulatorLauncher/Generators/Mame64.Generator.cs
emulatorLauncher/Generators/ScummVm.Generator.cs

MAME64:
Add arccabview shader preset
Add brightness, gamma and contrast adjustment
CITRA-QT
Add language setting update in nand
SCUMMVM
Add extrapath and themepath in ini
(folder shared with libretro core)

MAME64, citra-qt & scummvm stuff

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/BigPEmu.Generator.cs
emulatorLauncher/Generators/LibRetro.Generator.cs
emulatorLauncher/Generators/Mame64.Generator.cs

MAME64: add GLSL shaders with 3 shaders per default
BIGPEMU: add missing features
Added custom retroachievements sound capability

MAME64 & bigpemu & CHEEVOS sound

---

.emulationstation/es_features.cfg
batocera-systems/Resources/batocera-systems.json
batocera-systems/batocera-systems.csproj
emulatorLauncher/Generators/Dolphin.Controllers.cs
emulatorLauncher/Generators/Duckstation.Controllers.cs
emulatorLauncher/Generators/Duckstation.Generator.cs
emulatorLauncher/Generators/MessSystem.cs
emulatorLauncher/Generators/Pcsx2.Controllers.cs
emulatorLauncher/Generators/ZaccariaPinball.Generator.cs
emulatorLauncher/Installer.cs
emulatorLauncher/Program.cs
emulatorLauncher/emulatorLauncher.csproj

- MESS GP32 addition (1 feature) + BIOS check
**Duckstation**:
- New version exe declaration
- controllers autoconfiguration
- Additional features

Addition of GP32 MESS system and duckstation new version adaptation

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/Dolphin.Generator.cs
emulatorLauncher/Generators/OpenMSX.Controllers.cs
emulatorLauncher/Generators/OpenMSX.Generator.cs

OpenMSX final

---

emulatorLauncher/Generators/Dolphin.Generator.cs
emulatorLauncher/Generators/Duckstation.Controllers.cs

Dolphin : align paths with libretro
Duckstation: fix change disc path and add hotkey for quitting

dolphin & duckstation fixes

---

.emulationstation/es_features.cfg

- Mame64: add 2 controller profiles

ADDITIONAL FEATURES

---

.emulationstation/es_features.cfg
.gitignore
emulatorLauncher/Common/Generator.cs
emulatorLauncher/Generators/Cxbx.Generator.cs
emulatorLauncher/Generators/vita3k.Generator.cs

- vita3k: fix vsync and surface sync
- cxbx: add language feature
- mugen: add padtokey

Vita3k, cxbx, mugen

---

emulatorLauncher/Generators/GsPlus.Generator.cs
emulatorLauncher/Generators/LibRetro.Generator.cs

- GameFocus - fix option
- GSPlus: add m3u with multidisk

Fix gamefocus function + GSPlus

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/Cemu.Generator.cs
emulatorLauncher/Generators/Citra.Generator.cs
emulatorLauncher/Generators/Cxbx.Generator.cs
emulatorLauncher/Generators/GsPlus.Generator.cs
emulatorLauncher/Generators/Rpcs3.Generator.cs
emulatorLauncher/Generators/Ryujinx.Generator.cs
emulatorLauncher/Generators/Xemu.Generator.cs
emulatorLauncher/Generators/Xenia.Generator.cs
emulatorLauncher/Generators/Yuzu.Generator.cs
emulatorLauncher/Generators/vita3k.Generator.cs

- Alignment with ES languages
- rpcs3 way of finding eboot.bin

Language choices cleaning for standalone emulators

---

emulatorLauncher/Generators/Rpcs3.Generator.cs

I corrected the version, now I can collaborate with this project as soon as possible

Customizing search for EBOOT.BIN, reduction of extra lines

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/Dolphin.Generator.cs
emulatorLauncher/Generators/MessSystem.cs

**Dolphin.ini, add feature:**
- Re-enable draw FPS
- Audio driver
- Dolby pro Logic II
MESS:
- add apple2gs to mame
- add apple2 gameio feature

Dolphin & MAME/MESS

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/AppleWin.Generator.cs
emulatorLauncher/Generators/LibRetro.CoreOptions.cs
emulatorLauncher/Generators/LibRetro.Generator.cs
emulatorLauncher/Generators/MessSystem.cs

- applewin
- MAME (apple2)
Multiplayer with sameboy core

2 discs (apple2) and multiplayer (gb)

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/LibRetro.CoreOptions.cs
emulatorLauncher/Generators/LibRetro.Generator.cs
emulatorLauncher/Generators/Mupen64.Generator.cs
emulatorLauncher/Installer.cs
emulatorLauncher/Program.cs
emulatorLauncher/emulatorLauncher.csproj

- Features for sameboy
- Added Mupen64Generator

sameboy + Mupen64 standalone

---

.emulationstation/es_features.cfg
emulatorLauncher/Generators/AmigaForever.Generator.cs
emulatorLauncher/Generators/Mame64.Controllers.cs
emulatorLauncher/Generators/Mame64.Generator.cs
emulatorLauncher/emulatorLauncher.csproj

Xinput, dualshock and switch pro supported

Mame controller autoconfig
